# Generated by Django 4.2.1 on 2023-11-17 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactspeaker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactspeaker',
            options={'verbose_name': 'contato', 'verbose_name_plural': 'contatos'},
        ),
        migrations.AlterField(
            model_name='contactspeaker',
            name='kind',
            field=models.CharField(choices=[('E', 'Email'), ('P', 'Telefone')], max_length=1, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='contactspeaker',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.speaker', verbose_name='palestrante'),
        ),
        migrations.AlterField(
            model_name='contactspeaker',
            name='value',
            field=models.CharField(max_length=255, verbose_name='valor'),
        ),
    ]
